#!/bin/bash

read -r -p "This script is potentially dangerous and has only been tested on 1 ubuntu 14.04 server, continue? [y/N] " response

if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
then

	# sync files
	# src: install dir
	# des: /usr/share/pyshared/trac/htdocs/
	# desL /usr/share/pyshared/trac/templates/
	rsync -aP htdocs/* /usr/share/pyshared/trac/htdocs/
	rsync -aP templates/* /usr/share/pyshared/trac/templates/

	echo 'DEtrac theme sync [ok]'

	# htdocs
	# sync symlinks
	# src: /usr/share/pyshared/trac/htdocs/
	# des: /usr/lib/python2.7/dist-packages/trac/htdocs
	rm -r /usr/lib/python2.7/dist-packages/trac/htdocs
	ln -s /usr/share/pyshared/trac/htdocs/ /usr/lib/python2.7/dist-packages/trac/htdocs

	echo 'htdocs symlink created at /usr/lib/python2.7/dist-packages/trac'

	# templates
	# sync symlinks
	# src: /usr/share/pyshared/trac/templates/
	# des: /usr/lib/python2.7/dist-packages/trac/templates
	rm -r /usr/lib/python2.7/dist-packages/trac/templates
	ln -s /usr/share/pyshared/trac/templates/ /usr/lib/python2.7/dist-packages/trac/templates

	echo 'templates symlink created at /usr/lib/python2.7/dist-packages/trac'

	sed -i.backup -e '/trac.css/s/^/#/' /usr/share/pyshared/trac/web/chrome.py
	sed -i.backup -e '/wiki.css/s/^/#/' /usr/share/pyshared/trac/wiki/web_ui.py
	sed -i.backup -e '/timeline.css/s/^/#/' /usr/share/pyshared/trac/timeline/web_ui.py
	sed -i.backup -e '/search.css/s/^/#/' /usr/share/pyshared/trac/search/web_ui.py
	sed -i.backup -e '/browser.css/s/^/#/' /usr/share/pyshared/trac/versioncontrol/web_ui/browser.py
	sed -i.backup -e '/report.css/s/^/#/' /usr/share/pyshared/trac/ticket/report.py
	sed -i.backup -e '/ticket.css/s/^/#/' /usr/share/pyshared/trac/ticket/web_ui.py

	echo 'edits made to files in /usr/share/pyshared/trac. Originals saved with .backup extension.'

	echo 'install complete [ok]'
	
	read -r -p "reload apache? [y/N] " response
	
	if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
	then
		service apache2 reload
	else
		echo 'you should reload apache for theme to take effect'
	fi

	echo 'all [OK]'

else

	echo 'bye :)'

fi
